# Port
server.port=8080


# PostgreSQL Database Connection
# spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
# spring.datasource.url=jdbc:postgresql://postgres-container:5432/auth_db
# spring.datasource.username=postgres
# spring.datasource.password=root123

spring.datasource.url=jdbc:postgresql://ep-restless-morning-a8ahhfh8-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_MSac7E0ypUov
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
